#pragma once

// TODO(aed3): Make this autogenerated

namespace pokesim::ability::tags {
struct Analytic {};
struct ClearBody {};
struct Competitive {};
struct Defiant {};
struct HoneyGather {};
struct Imposter {};
struct Infiltrator {};
struct IronFist {};
struct Levitate {};
struct LongReach {};
struct Plus {};
struct Prankster {};
struct Scrappy {};
struct StanceChange {};
struct Static {};
struct SweetVeil {};
struct Synchronize {};
struct Torrent {};
struct Trace {};
}  // namespace pokesim::ability::tags
