// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "AbilityPropertyTags.hpp"
#include "BattleTags.hpp"
#include "Current.hpp"
#include "ItemPropertyTags.hpp"
#include "MovePropertyTags.hpp"
#include "NatureTags.hpp"
#include "PokemonTags.hpp"
#include "RecycledEntities.hpp"
#include "RunEventTags.hpp"
#include "Selection.hpp"
#include "SimulationTags.hpp"
#include "StatusTags.hpp"
#include "TargetTags.hpp"
#include "TypeTags.hpp"
