#pragma once

// TODO(aed3): Make this autogenerated

namespace pokesim::item::tags {
struct AssaultVest {};
struct BrightPowder {};
struct ChoiceScarf {};
struct ChoiceSpecs {};
struct FocusSash {};
struct KingsRock {};
struct LifeOrb {};
struct LumBerry {};
struct MetronomeItem {};
struct MirrorHerb {};
struct QuickClaw {};
struct QuickPowder {};
struct RockyHelmet {};
}  // namespace pokesim::item::tags
