#pragma once
// TODO(aed3): Make this autogenerated

namespace pokesim::move::tags {
struct AllySwitch {};
struct FlashCannon {};
struct FuryAttack {};
struct KnockOff {};
struct Moonblast {};
struct QuiverDance {};
struct Reflect {};
struct Reversal {};
struct SpiritShackle {};
struct Splash {};
struct Thunderbolt {};
struct Transform {};
struct TripleArrows {};
struct VoltSwitch {};
struct WillOWisp {};
}  // namespace pokesim::move::tags
