// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "Bug.hpp"
#include "Dark.hpp"
#include "Dragon.hpp"
#include "Electric.hpp"
#include "Fairy.hpp"
#include "Fighting.hpp"
#include "Fire.hpp"
#include "Flying.hpp"
#include "Ghost.hpp"
#include "Grass.hpp"
#include "Ground.hpp"
#include "Ice.hpp"
#include "Normal.hpp"
#include "Poison.hpp"
#include "Psychic.hpp"
#include "Rock.hpp"
#include "Steel.hpp"
#include "Water.hpp"
