#pragma once

#include <Components/Tags/AbilityTags.hpp>
#include <Config/Require.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Types/Enums/Ability.hpp>
#include <utility>
// TODO(aed3): Make this autogenerated

namespace pokesim::ability::tags {
/*
 * Runs a function with a certain ability tag based on the passed in enum.
 * The `RunStruct` type should be a struct that accepts one template parameter that will be one of the ability tags with
 * a static `run` function.
 *
 * @code
 * template <typename Tag>
 * struct EmplaceTag {
 *   static void run(types::handle handle) { handle.emplace<Tag>(); }
 * };
 *
 * enumToTag<EmplaceTag>(dex::Ability::DEFIANT, handle);
 * @endcode
 */
template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
auto enumToTag(dex::Ability ability, RunArgs&&... args) {
  switch (ability) {
    case dex::Ability::CLEAR_BODY:   return RunStruct<ClearBody, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::COMPETITIVE:  return RunStruct<Competitive, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::DEFIANT:      return RunStruct<Defiant, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::HONEY_GATHER: return RunStruct<HoneyGather, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::INFILTRATOR:  return RunStruct<Infiltrator, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::IRON_FIST:    return RunStruct<IronFist, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::PLUS:         return RunStruct<Plus, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::STATIC:       return RunStruct<Static, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::SWEET_VEIL:   return RunStruct<SweetVeil, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::SYNCHRONIZE:  return RunStruct<Synchronize, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::TORRENT:      return RunStruct<Torrent, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Ability::TRACE:        return RunStruct<Trace, T...>::run(std::forward<RunArgs>(args)...);

    default: {
      POKESIM_REQUIRE_FAIL("Using a tag for ability that does not exist.");
      using ReturnType = std::invoke_result_t<decltype(&RunStruct<void, T...>::run), RunArgs...>;
      if constexpr (std::is_void_v<ReturnType>) {
        return;
      }
      else {
        return ReturnType{};
      }
    }
  }
}

template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
void forEach(const Pokedex& pokedex, RunArgs&&... args) {
  pokedex.forEachLoadedAbility(
    [&](dex::Ability ability) { enumToTag<RunStruct, T...>(ability, std::forward<RunArgs>(args)...); });
}

}  // namespace pokesim::ability::tags
