// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "AbilityEnumToTag.hpp"
#include "EnumToTag.hpp"
#include "ItemEnumToTag.hpp"
#include "ItemPropertyEnumToTag.hpp"
#include "MoveEnumToTag.hpp"
#include "MovePropertyEnumToTag.hpp"
#include "NatureEnumToTag.hpp"
#include "StatusEnumToTag.hpp"
#include "TypeEnumToTag.hpp"
