#pragma once

#include <Config/Require.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Types/Entity.hpp>
#include <Types/Enums/Item.hpp>
#include <Types/Registry.hpp>
#include <utility>

#include "../Items/headers.hpp"

// TODO(aed3): Make this autogenerated

namespace pokesim::dex {
/*
 * Runs a function with a certain item tag based on the passed in enum.
 * The `RunStruct` type should be a struct that accepts one template parameter that will be one of the item tags with
 * a static `run` function.
 *
 * @code
 * template <typename Tag>
 * struct EmplaceTag {
 *   static void run(types::handle handle) { handle.emplace<Tag>(); }
 * };
 *
 * enumToTag<EmplaceTag>(dex::Item::ASSAULT_VEST, handle);
 * @endcode
 */
template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
auto enumToTag(Item item, RunArgs&&... args) {
  switch (item) {
    case Item::ASSAULT_VEST:  return RunStruct<AssaultVest, T...>::run(std::forward<RunArgs>(args)...);
    case Item::BRIGHT_POWDER: return RunStruct<BrightPowder, T...>::run(std::forward<RunArgs>(args)...);
    case Item::CHOICE_SCARF:  return RunStruct<ChoiceScarf, T...>::run(std::forward<RunArgs>(args)...);
    case Item::CHOICE_SPECS:  return RunStruct<ChoiceSpecs, T...>::run(std::forward<RunArgs>(args)...);
    case Item::FOCUS_SASH:    return RunStruct<FocusSash, T...>::run(std::forward<RunArgs>(args)...);
    case Item::KINGS_ROCK:    return RunStruct<KingsRock, T...>::run(std::forward<RunArgs>(args)...);
    case Item::LIFE_ORB:      return RunStruct<LifeOrb, T...>::run(std::forward<RunArgs>(args)...);
    case Item::LUM_BERRY:     return RunStruct<LumBerry, T...>::run(std::forward<RunArgs>(args)...);
    case Item::METRONOME:     return RunStruct<MetronomeItem, T...>::run(std::forward<RunArgs>(args)...);
    case Item::MIRROR_HERB:   return RunStruct<MirrorHerb, T...>::run(std::forward<RunArgs>(args)...);
    case Item::QUICK_CLAW:    return RunStruct<QuickClaw, T...>::run(std::forward<RunArgs>(args)...);
    case Item::QUICK_POWDER:  return RunStruct<QuickPowder, T...>::run(std::forward<RunArgs>(args)...);
    case Item::ROCKY_HELMET:  return RunStruct<RockyHelmet, T...>::run(std::forward<RunArgs>(args)...);

    default: {
      POKESIM_REQUIRE_FAIL("Using a tag for item that does not exist.");
      using ReturnType = std::invoke_result_t<decltype(&RunStruct<void, T...>::run), RunArgs...>;
      if constexpr (std::is_void_v<ReturnType>) {
        return;
      }
      else {
        return ReturnType{};
      }
    }
  }
}

template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
void forEachItem(const Pokedex& pokedex, RunArgs&&... args) {
  pokedex.forEachLoadedItem([&](Item item) { enumToTag<RunStruct, T...>(item, std::forward<RunArgs>(args)...); });
}

// Assigns an item's tag to a handle
void emplaceTagFromEnum(Item item, types::handle handle);
void emplaceTagFromEnum(Item item, types::registry& registry, types::entity entity);

// Checks if the handle has the item's tag
bool hasTag(Item item, types::handle handle);
bool hasTag(Item item, const types::registry& registry, types::entity entity);
}  // namespace pokesim::dex
