#pragma once

#include <Components/Tags/ItemTags.hpp>
#include <Config/Require.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Types/Enums/Item.hpp>
#include <utility>
// TODO(aed3): Make this autogenerated

namespace pokesim::item::tags {
/*
 * Runs a function with a certain item tag based on the passed in enum.
 * The `RunStruct` type should be a struct that accepts one template parameter that will be one of the item tags with
 * a static `run` function.
 *
 * @code
 * template <typename Tag>
 * struct EmplaceTag {
 *   static void run(types::handle handle) { handle.emplace<Tag>(); }
 * };
 *
 * enumToTag<EmplaceTag>(dex::Item::ASSAULT_VEST, handle);
 * @endcode
 */
template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
auto enumToTag(dex::Item item, RunArgs&&... args) {
  switch (item) {
    case dex::Item::ASSAULT_VEST:  return RunStruct<AssaultVest, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Item::BRIGHT_POWDER: return RunStruct<BrightPowder, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Item::CHOICE_SCARF:  return RunStruct<ChoiceScarf, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Item::CHOICE_SPECS:  return RunStruct<ChoiceSpecs, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Item::FOCUS_SASH:    return RunStruct<FocusSash, T...>::run(std::forward<RunArgs>(args)...);
    case dex::Item::LIFE_ORB:      return RunStruct<LifeOrb, T...>::run(std::forward<RunArgs>(args)...);

    default: {
      POKESIM_REQUIRE_FAIL("Using a tag for item that does not exist.");
      using ReturnType = std::invoke_result_t<decltype(&RunStruct<void, T...>::run), RunArgs...>;
      if constexpr (std::is_void_v<ReturnType>) {
        return;
      }
      else {
        return ReturnType{};
      }
    }
  }
}

template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
void forEach(const Pokedex& pokedex, RunArgs&&... args) {
  pokedex.forEachLoadedItem([&](dex::Item item) { enumToTag<RunStruct, T...>(item, std::forward<RunArgs>(args)...); });
}
}  // namespace pokesim::item::tags
