#pragma once

#include <Config/Require.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Types/Entity.hpp>
#include <Types/Enums/Move.hpp>
#include <Types/Registry.hpp>
#include <utility>

#include "../Moves/headers.hpp"

// TODO(aed3): Make this autogenerated

namespace pokesim::dex {
/*
 * Runs a function with a certain move tag based on the passed in enum.
 * The `RunStruct` type should be a struct that accepts one template parameter that will be one of the move tags with
 * a static `run` function.
 *
 * @code
 * template <typename Tag>
 * struct EmplaceTag {
 *   static void run(types::handle handle) { handle.emplace<Tag>(); }
 * };
 *
 * enumToTag<EmplaceTag>(dex::Move::FURY_ATTACK, handle);
 * @endcode
 */
template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
auto enumToTag(Move move, RunArgs&&... args) {
  switch (move) {
    case Move::ALLY_SWITCH:    return RunStruct<AllySwitch, T...>::run(std::forward<RunArgs>(args)...);
    case Move::FLASH_CANNON:   return RunStruct<FlashCannon, T...>::run(std::forward<RunArgs>(args)...);
    case Move::FURY_ATTACK:    return RunStruct<FuryAttack, T...>::run(std::forward<RunArgs>(args)...);
    case Move::KNOCK_OFF:      return RunStruct<KnockOff, T...>::run(std::forward<RunArgs>(args)...);
    case Move::MOONBLAST:      return RunStruct<Moonblast, T...>::run(std::forward<RunArgs>(args)...);
    case Move::QUIVER_DANCE:   return RunStruct<QuiverDance, T...>::run(std::forward<RunArgs>(args)...);
    case Move::REFLECT:        return RunStruct<Reflect, T...>::run(std::forward<RunArgs>(args)...);
    case Move::REVERSAL:       return RunStruct<Reversal, T...>::run(std::forward<RunArgs>(args)...);
    case Move::SPIRIT_SHACKLE: return RunStruct<SpiritShackle, T...>::run(std::forward<RunArgs>(args)...);
    case Move::SPLASH:         return RunStruct<Splash, T...>::run(std::forward<RunArgs>(args)...);
    case Move::THUNDERBOLT:    return RunStruct<Thunderbolt, T...>::run(std::forward<RunArgs>(args)...);
    case Move::TRANSFORM:      return RunStruct<Transform, T...>::run(std::forward<RunArgs>(args)...);
    case Move::TRIPLE_ARROWS:  return RunStruct<TripleArrows, T...>::run(std::forward<RunArgs>(args)...);
    case Move::VOLT_SWITCH:    return RunStruct<VoltSwitch, T...>::run(std::forward<RunArgs>(args)...);
    case Move::WILL_O_WISP:    return RunStruct<WillOWisp, T...>::run(std::forward<RunArgs>(args)...);

    default: {
      POKESIM_REQUIRE_FAIL("Using a tag for move that does not exist.");
      using ReturnType = std::invoke_result_t<decltype(&RunStruct<void, T...>::run), RunArgs...>;
      if constexpr (std::is_void_v<ReturnType>) {
        return;
      }
      else {
        return ReturnType{};
      }
    }
  }
}

template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
void forEachMove(const Pokedex& pokedex, RunArgs&&... args) {
  pokedex.forEachLoadedMove([&](Move move) { enumToTag<RunStruct, T...>(move, std::forward<RunArgs>(args)...); });
}

// Assigns a move's tag to a handle
void emplaceTagFromEnum(Move move, types::handle handle);
void emplaceTagFromEnum(Move move, types::registry& registry, types::entity entity);

// Checks if the handle has the move's tag
bool hasTag(Move move, types::handle handle);
bool hasTag(Move move, const types::registry& registry, types::entity entity);
}  // namespace pokesim::dex
