#pragma once

#include <Config/Require.hpp>
#include <Types/Enums/Species.hpp>
#include <utility>

#include "../Species/headers.hpp"

// TODO(aed3): Make this autogenerated

namespace pokesim::dex {
/*
 * Runs a function with a certain species tag based on the passed in enum.
 * The `RunStruct` type should be a struct that accepts one template parameter that will be one of the species tags with
 * a static `run` function.
 *
 * @code
 * template <typename Tag>
 * struct EmplaceTag {
 *   static void run(types::handle handle) { handle.emplace<Tag>(); }
 * };
 *
 * enumToTag<EmplaceTag>(dex::Species::BULBASAUR, handle);
 * @endcode
 */
template <template <typename, typename...> typename RunStruct, typename... T, typename... RunArgs>
auto enumToTag(Species species, RunArgs&&... args) {
  switch (species) {
    case Species::DITTO:             return RunStruct<Ditto, T...>::run(std::forward<RunArgs>(args)...);
    case Species::AMPHAROS:          return RunStruct<Ampharos, T...>::run(std::forward<RunArgs>(args)...);
    case Species::GARDEVOIR:         return RunStruct<Gardevoir, T...>::run(std::forward<RunArgs>(args)...);
    case Species::CLAYDOL:           return RunStruct<Claydol, T...>::run(std::forward<RunArgs>(args)...);
    case Species::EMPOLEON:          return RunStruct<Empoleon, T...>::run(std::forward<RunArgs>(args)...);
    case Species::MAGNEZONE:         return RunStruct<Magnezone, T...>::run(std::forward<RunArgs>(args)...);
    case Species::BRAVIARY:          return RunStruct<Braviary, T...>::run(std::forward<RunArgs>(args)...);
    case Species::PANGORO:           return RunStruct<Pangoro, T...>::run(std::forward<RunArgs>(args)...);
    case Species::AEGISLASH:         return RunStruct<Aegislash, T...>::run(std::forward<RunArgs>(args)...);
    case Species::SHIELD_AEGISLASH:  return RunStruct<ShieldAegislash, T...>::run(std::forward<RunArgs>(args)...);
    case Species::BLADE_AEGISLASH:   return RunStruct<BladeAegislash, T...>::run(std::forward<RunArgs>(args)...);
    case Species::DECIDUEYE:         return RunStruct<Decidueye, T...>::run(std::forward<RunArgs>(args)...);
    case Species::HISUIAN_DECIDUEYE: return RunStruct<HisuianDecidueye, T...>::run(std::forward<RunArgs>(args)...);
    case Species::RIBOMBEE:          return RunStruct<Ribombee, T...>::run(std::forward<RunArgs>(args)...);
    case Species::GRIMMSNARL:        return RunStruct<Grimmsnarl, T...>::run(std::forward<RunArgs>(args)...);
    case Species::DRAGAPULT:         return RunStruct<Dragapult, T...>::run(std::forward<RunArgs>(args)...);

    default: {
      POKESIM_REQUIRE_FAIL("Using a tag for species that does not exist.");
      using ReturnType = std::invoke_result_t<decltype(&RunStruct<void, T...>::run), RunArgs...>;
      if constexpr (std::is_void_v<ReturnType>) {
        return;
      }
      else {
        return ReturnType{};
      }
    }
  }
}
}  // namespace pokesim::dex
