// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "CalcDamageSpecifics.hpp"
#include "Decisions.hpp"
#include "ManageActionQueue.hpp"
#include "RandomChance.hpp"
#include "SimulateTurn.hpp"
#include "SimulateTurnDebugChecks.hpp"
