#pragma once

#if !defined(NDEBUG) || defined(POKESIM_ENABLE_TESTING)
#define POKESIM_DEBUG_CHECK_UTILITIES
#endif

#if defined(POKESIM_ENTITY_VIEWER) && defined(POKESIM_USE_COMBINED_SOURCE_AND_HEADER_FILES)
#undef POKESIM_ENTITY_VIEWER
#endif
