#include <Components/Names/ItemNames.hpp>
#include <Components/Tags/ItemPropertyTags.hpp>
#include <Config/Require.hpp>
#include <Pokedex/EnumToTag/ItemPropertyEnumToTag.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Types/Entity.hpp>
#include <Types/Enums/Item.hpp>
#include <Types/Registry.hpp>
#include <entt/entity/handle.hpp>

#include "../Items/headers.hpp"

// TODO(aed3): Make this and the individual item files autogenerated

namespace pokesim {
namespace {
template <typename Tag>
struct EmplaceItemTag {
  static void run(types::handle handle) { handle.emplace<Tag>(); }
};

template <typename Item>
struct BuildItem {
 private:
  enum class Optional : std::uint8_t {
    itemProperties,
  };

  template <auto Member>
  using void_t = std::void_t<decltype(Member)>;

  template <Optional, typename, typename V = void>
  struct has : std::false_type {};
  template <typename Type>
  struct has<Optional::itemProperties, Type, void_t<Type::itemProperties>> : std::true_type {};

 public:
  static types::entity build(types::registry& registry, GameMechanics gameMechanic) {
    types::handle item{registry, registry.create()};

    item.emplace<ItemName>(Item::name(gameMechanic));

    if constexpr (has<Optional::itemProperties, Item>::value) {
      item::tags::enumToTag<EmplaceItemTag>(Item::itemProperties(gameMechanic), item);
    }

    return item.entity();
  }
};
types::entity buildByGameMechanic(dex::Item item, types::registry& registry, GameMechanics gameMechanic) {
  // Tidy check ignored because "using namespace" is in function
  using namespace pokesim::dex;  // NOLINT(google-build-using-namespace)
  switch (item) {
    case Item::ASSAULT_VEST:  return BuildItem<AssaultVest>::build(registry, gameMechanic);
    case Item::BRIGHT_POWDER: return BuildItem<BrightPowder>::build(registry, gameMechanic);
    case Item::CHOICE_SCARF:  return BuildItem<ChoiceScarf>::build(registry, gameMechanic);
    case Item::CHOICE_SPECS:  return BuildItem<ChoiceSpecs>::build(registry, gameMechanic);
    case Item::FOCUS_SASH:    return BuildItem<FocusSash>::build(registry, gameMechanic);
    case Item::LIFE_ORB:      return BuildItem<LifeOrb>::build(registry, gameMechanic);

    default: break;
  }

  POKESIM_REQUIRE_FAIL("Building an item that is not yet supported.");
  return types::entity{};
}
}  // namespace

types::entity Pokedex::buildItem(dex::Item item, types::registry& registry) const {
  if (isGameMechanic(GameMechanics::SCARLET_VIOLET)) {
    return buildByGameMechanic(item, registry, GameMechanics::SCARLET_VIOLET);
  }

  POKESIM_REQUIRE_FAIL("Building for a game that is not yet supported.");
  return types::entity{};
}
}  // namespace pokesim
