#include <Components/Accuracy.hpp>
#include <Components/AddedTargets.hpp>
#include <Components/BaseEffectChance.hpp>
#include <Components/BasePower.hpp>
#include <Components/Boosts.hpp>
#include <Components/HitCount.hpp>
#include <Components/Names/MoveNames.hpp>
#include <Components/Names/TypeNames.hpp>
#include <Components/Pokedex/PP.hpp>
#include <Components/Priority.hpp>
#include <Components/Tags/MovePropertyTags.hpp>
#include <Components/Tags/MoveTags.hpp>
#include <Components/Tags/Selection.hpp>
#include <Components/Tags/TargetTags.hpp>
#include <Config/Require.hpp>
#include <Pokedex/EnumToTag/MovePropertyEnumToTag.hpp>
#include <Pokedex/EnumToTag/StatusEnumToTag.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Simulation/Simulation.hpp>
#include <Types/Entity.hpp>
#include <Types/Enums/AddedTargets.hpp>
#include <Types/Enums/Move.hpp>
#include <Types/Enums/MoveCategory.hpp>
#include <Types/Enums/MoveTarget.hpp>
#include <Types/Move.hpp>
#include <Types/Random.hpp>
#include <Types/Registry.hpp>
#include <Types/Stats.hpp>
#include <cstdint>
#include <entt/entity/registry.hpp>
#include <type_traits>

#include "../Moves/headers.hpp"

// TODO(aed3): Make this and the individual move files autogenerated

namespace pokesim {
namespace {
template <typename BuildMoveTag, typename Move, typename MoveTag>
struct BuildMove {
 private:
  enum class Optional : std::uint8_t {
    accuracy,
    basePower,
    hitCount,
    targetPrimaryEffect,
    targetSecondaryEffect,
    sourcePrimaryEffect,
    sourceSecondaryEffect,
    moveProperties,

    chance,
    atkBoost,
    defBoost,
    spaBoost,
    spdBoost,
    speBoost,
    status,
  };

  enum class MoveEffectKind : std::uint8_t {
    primary,
    secondary,
  };

  template <auto Member>
  using void_t = std::void_t<decltype(Member)>;

  template <Optional, typename, typename V = void>
  struct has : std::false_type {};
  template <typename Type>
  struct has<Optional::accuracy, Type, void_t<Type::accuracy>> : std::true_type {};
  template <typename Type>
  struct has<Optional::basePower, Type, void_t<Type::basePower>> : std::true_type {};
  template <typename Type>
  struct has<Optional::hitCount, Type, void_t<Type::hitCount>> : std::true_type {};
  template <typename Type>
  struct has<Optional::targetPrimaryEffect, Type, std::void_t<typename Type::targetPrimaryEffect>> : std::true_type {};
  template <typename Type>
  struct has<Optional::targetSecondaryEffect, Type, std::void_t<typename Type::targetSecondaryEffect>>
      : std::true_type {};
  template <typename Type>
  struct has<Optional::sourcePrimaryEffect, Type, std::void_t<typename Type::sourcePrimaryEffect>> : std::true_type {};
  template <typename Type>
  struct has<Optional::sourceSecondaryEffect, Type, std::void_t<typename Type::sourceSecondaryEffect>>
      : std::true_type {};
  template <typename Type>
  struct has<Optional::moveProperties, Type, void_t<Type::moveProperties>> : std::true_type {};
  template <typename Type>
  struct has<Optional::chance, Type, void_t<Type::chance>> : std::true_type {};
  template <typename Type>
  struct has<Optional::atkBoost, Type, void_t<Type::atkBoost>> : std::true_type {};
  template <typename Type>
  struct has<Optional::defBoost, Type, void_t<Type::defBoost>> : std::true_type {};
  template <typename Type>
  struct has<Optional::spaBoost, Type, void_t<Type::spaBoost>> : std::true_type {};
  template <typename Type>
  struct has<Optional::spdBoost, Type, void_t<Type::spdBoost>> : std::true_type {};
  template <typename Type>
  struct has<Optional::speBoost, Type, void_t<Type::speBoost>> : std::true_type {};
  template <typename Type>
  struct has<Optional::status, Type, void_t<Type::status>> : std::true_type {};

  struct EntitySetup {
    using EntityList = entt::view<entt::get_t<BuildMoveTag, MoveTag>>;
    types::registry* registry;
    const EntityList* list;
    std::size_t size;

    EntitySetup(types::registry& registry_, const EntityList& list_)
        : registry(&registry_), list(&list_), size(list->size_hint()) {}

    template <typename Component>
    void add(const Component& component) {
      registry->storage<Component>().reserve(size);
      if constexpr (std::is_empty_v<Component>) {
        registry->insert<Component>(list->begin(), list->end());
      }
      else {
        registry->insert(list->begin(), list->end(), component);
      }
    }

    template <typename... Types>
    bool any_of() {
      return std::any_of(list->begin(), list->end(), [&](types::entity entity) {
        return registry->template any_of<Types...>(entity);
      });
    }
  };

  template <typename Tag>
  struct AddFromEnum {
    static void run(EntitySetup& setup) { setup.add(Tag{}); }
  };

  template <typename EffectData, MoveEffectKind moveEffectKind>
  static void buildEffect(EntitySetup& setup, GameMechanics gameMechanic) {
    if constexpr (moveEffectKind == MoveEffectKind::primary) {
      static_assert(
        !has<Optional::chance, EffectData>::value,
        "Primary effects cannot have a chance to happen because they always happen if the move is successful.");

      POKESIM_REQUIRE(
        !setup.template any_of<move::effect::tags::Secondary>(),
        "Moves can only have primary or secondary effects, not both.");

      setup.add(move::effect::tags::Primary{});
    }
    else {
      POKESIM_REQUIRE(
        !setup.template any_of<move::effect::tags::Primary>(),
        "Moves can only have secondary or primary effects, not both.");

      types::percentChance chance = Constants::MoveBaseEffectChance::DEFAULT;
      if constexpr (has<Optional::chance, EffectData>::value) {
        chance = EffectData::chance(gameMechanic);
      }
      setup.add(move::effect::tags::Secondary{});
      setup.add(BaseEffectChance{chance});
    }

    if constexpr (has<Optional::atkBoost, EffectData>::value) {
      setup.add(AtkBoost{EffectData::atkBoost(gameMechanic)});
    }

    if constexpr (has<Optional::defBoost, EffectData>::value) {
      setup.add(DefBoost{EffectData::defBoost(gameMechanic)});
    }

    if constexpr (has<Optional::spaBoost, EffectData>::value) {
      setup.add(SpaBoost{EffectData::spaBoost(gameMechanic)});
    }

    if constexpr (has<Optional::spdBoost, EffectData>::value) {
      setup.add(SpdBoost{EffectData::spdBoost(gameMechanic)});
    }

    if constexpr (has<Optional::speBoost, EffectData>::value) {
      setup.add(SpeBoost{EffectData::speBoost(gameMechanic)});
    }

    if constexpr (has<Optional::status, EffectData>::value) {
      status::tags::enumToTag<AddFromEnum>(EffectData::status(gameMechanic), setup);
    }
  }

 public:
  static void build(types::registry& registry, GameMechanics gameMechanic) {
    auto list = registry.view<BuildMoveTag, MoveTag>();
    if (list.begin() == list.end()) {
      return;
    }

    EntitySetup setup{registry, list};

    if (std::is_same_v<BuildMoveTag, internal::tags::BuildPokedexMove>) {
      setup.add(MoveName{Move::name(gameMechanic)});
      setup.add(Pp{Move::basePp(gameMechanic)});
    }

    setup.add(TypeName{Move::type(gameMechanic)});
    switch (Move::category(gameMechanic)) {
      case dex::MoveCategory::PHYSICAL: {
        POKESIM_REQUIRE(
          !(setup.template any_of<move::tags::Special, move::tags::Status>()),
          "A move can only have one category.");

        setup.add(move::tags::Physical{});
        break;
      }
      case dex::MoveCategory::SPECIAL: {
        POKESIM_REQUIRE(
          !(setup.template any_of<move::tags::Physical, move::tags::Status>()),
          "A move can only have one category.");

        setup.add(move::tags::Special{});
        break;
      }
      case dex::MoveCategory::STATUS: {
        POKESIM_REQUIRE(
          !(setup.template any_of<move::tags::Physical, move::tags::Special>()),
          "A move can only have one category.");
        setup.add(move::tags::Status{});
        break;
      }
    }

    if constexpr (has<Optional::accuracy, Move>::value) {
      setup.add(Accuracy{Move::accuracy(gameMechanic)});
    }
    if constexpr (has<Optional::basePower, Move>::value) {
      setup.add(BasePower{Move::basePower(gameMechanic)});
    }
    if constexpr (has<Optional::hitCount, Move>::value) {
      setup.add(HitCount{Move::hitCount(gameMechanic)});
    }

    if constexpr (has<Optional::sourcePrimaryEffect, Move>::value) {
      buildEffect<typename Move::sourcePrimaryEffect, MoveEffectKind::primary>(setup);
      POKESIM_REQUIRE(
        !(setup.template any_of<move::effect::tags::MoveTarget>()),
        "Moves effects can only affect the target or source, not both.");
      setup.add(move::effect::tags::MoveSource{});
    }

    if constexpr (has<Optional::targetPrimaryEffect, Move>::value) {
      POKESIM_REQUIRE(
        !(setup.template any_of<move::effect::tags::MoveSource>()),
        "Moves effects can only affect the target or source, not both.");
      buildEffect<typename Move::targetPrimaryEffect, MoveEffectKind::primary>(setup, gameMechanic);
      setup.add(move::effect::tags::MoveTarget{});
    }

    if constexpr (has<Optional::sourceSecondaryEffect, Move>::value) {
      POKESIM_REQUIRE(
        !(setup.template any_of<move::effect::tags::MoveTarget>()),
        "Moves effects can only affect the target or source, not both.");
      buildEffect<typename Move::sourceSecondaryEffect, MoveEffectKind::secondary>(setup, gameMechanic);
      setup.add(move::effect::tags::MoveSource{});
    }

    if constexpr (has<Optional::targetSecondaryEffect, Move>::value) {
      POKESIM_REQUIRE(
        !(setup.template any_of<move::effect::tags::MoveSource>()),
        "Moves effects can only affect the target or source, not both.");
      buildEffect<typename Move::targetSecondaryEffect, MoveEffectKind::secondary>(setup, gameMechanic);
      setup.add(move::effect::tags::MoveTarget{});
    }

    if constexpr (has<Optional::moveProperties, Move>::value) {
      move::tags::enumToTag<AddFromEnum>(Move::moveProperties(gameMechanic), setup);
    }

    switch (Move::target(gameMechanic)) {
      case MoveTarget::ANY_SINGLE_TARGET: {
        setup.add(move::tags::AnySingleTarget{});
        break;
      }
      case MoveTarget::ANY_SINGLE_FOE: {
        setup.add(move::tags::AnySingleFoe{});
        break;
      }
      case MoveTarget::ANY_SINGLE_ALLY: {
        setup.add(move::tags::AnySingleAlly{});
        break;
      }
      case MoveTarget::ALLY_OR_SELF: {
        setup.add(move::tags::AllyOrSelf{});
        break;
      }
      case MoveTarget::SELF: {
        setup.add(move::tags::Self{});
        break;
      }
      case MoveTarget::ALL_FOES: {
        setup.add(move::tags::AllFoes{});
        setup.add(move::added_targets::tags::TargetAlly{});
        break;
      }
      case MoveTarget::ALLIES_AND_FOES: {
        setup.add(move::tags::AlliesAndFoes{});
        setup.add(move::added_targets::tags::TargetAlly{});
        setup.add(move::added_targets::tags::UserAlly{});
        break;
      }
      case MoveTarget::ALLIES_AND_SELF: {
        setup.add(move::tags::AlliesAndSelf{});
        // Deliberately not USER_ALLY as the target of AlliesAndSelf moves is the user
        setup.add(move::added_targets::tags::TargetAlly{});
        break;
      }
      case MoveTarget::FOE_SIDE: {
        setup.add(move::tags::FoeSide{});
        setup.add(move::added_targets::tags::TargetSide{});
        break;
      }
      case MoveTarget::ALLY_SIDE: {
        setup.add(move::tags::AllySide{});
        setup.add(move::added_targets::tags::UserSide{});
        break;
      }
      case MoveTarget::FIELD: {
        setup.add(move::tags::Field{});
        setup.add(move::added_targets::tags::Field{});
        break;
      }
      case MoveTarget::ALLY_TEAM: {
        setup.add(move::tags::AllyTeam{});
        setup.add(move::added_targets::tags::UserSide{});
        break;
      }
      case MoveTarget::RETALIATION: {
        setup.add(move::tags::Retaliation{});
        break;
      }
      case MoveTarget::RANDOM_FOE: {
        setup.add(move::tags::RandomFoe{});
        break;
      }
      default: break;
    }

    if (std::is_same_v<BuildMoveTag, internal::tags::BuildPokedexMove>) {
      registry.remove<MoveTag>(list.begin(), list.end());
    }
  }
};

template <typename BuildMoveTag>
struct BuildMoves {
 private:
  template <typename Move, typename MoveTag>
  static void buildActionMoveFromView(types::registry& registry, GameMechanics gameMechanics) {
    BuildMove<BuildMoveTag, Move, MoveTag>::build(registry, gameMechanics);
  }

  static void buildActionMoveByGameMechanic(types::registry& registry, GameMechanics gameMechanic) {
    using namespace pokesim::dex;  // NOLINT(google-build-using-namespace)

    buildActionMoveFromView<FuryAttack, move::tags::FuryAttack>(registry, gameMechanic);
    buildActionMoveFromView<KnockOff, move::tags::KnockOff>(registry, gameMechanic);
    buildActionMoveFromView<Moonblast, move::tags::Moonblast>(registry, gameMechanic);
    buildActionMoveFromView<QuiverDance, move::tags::QuiverDance>(registry, gameMechanic);
    buildActionMoveFromView<Splash, move::tags::Splash>(registry, gameMechanic);
    buildActionMoveFromView<Thunderbolt, move::tags::Thunderbolt>(registry, gameMechanic);
    buildActionMoveFromView<WillOWisp, move::tags::WillOWisp>(registry, gameMechanic);
  }

 public:
  static void build(const Pokedex& pokedex, types::registry& registry) {
    if (pokedex.isGameMechanic(GameMechanics::SCARLET_VIOLET)) {
      buildActionMoveByGameMechanic(registry, GameMechanics::SCARLET_VIOLET);
      return;
    }

    POKESIM_REQUIRE_FAIL("Building for a game that is not yet supported.");
  }
};
}  // namespace

void Pokedex::buildMoves(types::registry& registry) const {
  if (!registry.view<internal::tags::BuildActionMove>().empty()) {
    BuildMoves<internal::tags::BuildActionMove>::build(*this, registry);
  }

  if (!registry.view<internal::tags::BuildPokedexMove>().empty()) {
    BuildMoves<internal::tags::BuildPokedexMove>::build(*this, registry);
  }
}
}  // namespace pokesim
