#include <Config/Require.hpp>
#include <Pokedex/Pokedex.hpp>
#include <Types/Entity.hpp>
#include <Types/Enums/Species.hpp>
#include <Types/Registry.hpp>
#include <cstdint>
#include <type_traits>

#include "../Species/headers.hpp"
#include "SpeciesDexDataSetup.hpp"

// TODO(aed3): Make this and the individual species files autogenerated

namespace pokesim {
namespace {
template <typename T>
struct BuildSpecies {
 private:
  enum class Optional : std::uint8_t {
    primaryAbility,
    secondaryAbility,
    hiddenAbility,
  };

  template <auto Member>
  using void_t = std::void_t<decltype(Member)>;

  template <Optional, typename = T, typename V = void>
  struct has : std::false_type {};
  template <typename Type>
  struct has<Optional::primaryAbility, Type, void_t<Type::primaryAbility>> : std::true_type {};
  template <typename Type>
  struct has<Optional::secondaryAbility, Type, void_t<Type::secondaryAbility>> : std::true_type {};
  template <typename Type>
  struct has<Optional::hiddenAbility, Type, void_t<Type::hiddenAbility>> : std::true_type {};

 public:
  static types::entity build(types::registry& registry, GameMechanics gameMechanic) {
    dex::internal::SpeciesDexDataSetup species(registry);

    species.setName(T::name(gameMechanic));
    species.setBaseStats(
      T::hp(gameMechanic),
      T::atk(gameMechanic),
      T::def(gameMechanic),
      T::spa(gameMechanic),
      T::spd(gameMechanic),
      T::spe(gameMechanic));
    species.setType(T::type(gameMechanic).type1(), T::type(gameMechanic).type2());

    if constexpr (has<Optional::primaryAbility>::value) {
      species.setPrimaryAbility(T::primaryAbility(gameMechanic));
    }
    if constexpr (has<Optional::secondaryAbility>::value) {
      species.setSecondaryAbility(T::secondaryAbility(gameMechanic));
    }
    if constexpr (has<Optional::hiddenAbility>::value) {
      species.setHiddenAbility(T::hiddenAbility(gameMechanic));
    }

    return species.entity();
  }
};

types::entity buildByGameMechanic(dex::Species species, types::registry& registry, GameMechanics gameMechanic) {
  // Tidy check ignored because "using namespace" is in function
  using namespace pokesim::dex;  // NOLINT(google-build-using-namespace)
  switch (species) {
    case Species::AMPHAROS:  return BuildSpecies<Ampharos>::build(registry, gameMechanic);
    case Species::GARDEVOIR: return BuildSpecies<Gardevoir>::build(registry, gameMechanic);
    case Species::EMPOLEON:  return BuildSpecies<Empoleon>::build(registry, gameMechanic);
    case Species::PANGORO:   return BuildSpecies<Pangoro>::build(registry, gameMechanic);
    case Species::RIBOMBEE:  return BuildSpecies<Ribombee>::build(registry, gameMechanic);
    case Species::DRAGAPULT: return BuildSpecies<Dragapult>::build(registry, gameMechanic);

    default: break;
  }

  POKESIM_REQUIRE_FAIL("Building a species that is not yet supported.");
  return entt::entity{};
}
}  // namespace

types::entity Pokedex::buildSpecies(dex::Species species, types::registry& registry) const {
  if (isGameMechanic(GameMechanics::SCARLET_VIOLET)) {
    return buildByGameMechanic(species, registry, GameMechanics::SCARLET_VIOLET);
  }

  POKESIM_REQUIRE_FAIL("Building for a game that is not yet supported.");
  return types::entity{};
}
}  // namespace pokesim
