// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "AssaultVest.hpp"
#include "BrightPowder.hpp"
#include "ChoiceScarf.hpp"
#include "ChoiceSpecs.hpp"
#include "FocusSash.hpp"
#include "KingsRock.hpp"
#include "LifeOrb.hpp"
#include "LumBerry.hpp"
#include "Metronome.hpp"
#include "MirrorHerb.hpp"
#include "QuickClaw.hpp"
#include "QuickPowder.hpp"
#include "RockyHelmet.hpp"
