// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "Battle.hpp"
#include "BattleTree.hpp"
#include "ChoiceLock.hpp"
#include "Current.hpp"
#include "FaintQueue.hpp"
#include "FoeSide.hpp"
#include "LastUsedMove.hpp"
#include "MoveSlots.hpp"
#include "Pokemon.hpp"
#include "RecycledEntities.hpp"
#include "Side.hpp"
#include "Sides.hpp"
#include "Team.hpp"
