const fs = require('fs');
const path = require('path');
const {fullPath, toRelative, ignoredFile, autoGeneratedFileStart} = require('../utils');

const headerFileName = 'headers.hpp';

const createHeadersFile = (folder) => {
  const folderHeadersFileName = path.join(folder, headerFileName);
  const headersFileExists = fs.existsSync(folderHeadersFileName);

  const files = fs.readdirSync(folder).map(file => path.join(folder, file));
  const headerFiles = [];

  for (const file of files) {
    if (fs.statSync(file).isDirectory()) {
      const subFolderHeaderFiles = createHeadersFile(file);
      if (subFolderHeaderFiles) {
        headerFiles.push(...subFolderHeaderFiles);
        continue;
      }

      for (const subFile of fs.readdirSync(file)) {
        if (path.extname(subFile) === '.hpp') {
          headerFiles.push(path.join(file, subFile));
        }
      }
      continue;
    }
    if (path.extname(file) === '.hpp' && file !== folderHeadersFileName && !ignoredFile.includes(path.basename(file))) {
      headerFiles.push(file);
    }
  }

  if (headersFileExists) {
    headerFiles.sort();
    fs.writeFileSync(folderHeadersFileName, autoGeneratedFileStart + '\n\n#pragma once\n\n');
    fs.appendFileSync(
      folderHeadersFileName, headerFiles.map(file => `#include "${toRelative(file, folder)}"`).join('\n'));
    return headerFiles;
  }

  return null;
};

createHeadersFile(fullPath('src'));