// AUTO GENERATED FILE, DO NOT EDIT

#pragma once

#include "Ability.hpp"
#include "ActionOrder.hpp"
#include "AddedTargets.hpp"
#include "BattleFormat.hpp"
#include "DamageRollKind.hpp"
#include "GameMechanics.hpp"
#include "Gender.hpp"
#include "Item.hpp"
#include "Move.hpp"
#include "MoveCategory.hpp"
#include "MoveTarget.hpp"
#include "Nature.hpp"
#include "PlayerSideId.hpp"
#include "PseudoWeather.hpp"
#include "SideCondition.hpp"
#include "Slot.hpp"
#include "Species.hpp"
#include "StabBoostKind.hpp"
#include "Stat.hpp"
#include "Status.hpp"
#include "Terrain.hpp"
#include "Type.hpp"
#include "TypeEffectiveness.hpp"
#include "Volatile.hpp"
#include "Weather.hpp"