#pragma once

#include "Ability.hpp"
#include "BattleFormat.hpp"
#include "DamageRollKind.hpp"
#include "GameMechanics.hpp"
#include "Gender.hpp"
#include "Item.hpp"
#include "Move.hpp"
#include "Nature.hpp"
#include "PlayerSideId.hpp"
#include "Species.hpp"
#include "Stat.hpp"
#include "Status.hpp"
#include "TargetSlot.hpp"
#include "Type.hpp"