// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "Burn.hpp"
#include "ChoiceLock.hpp"
#include "Flinch.hpp"
#include "Freeze.hpp"
#include "Paralysis.hpp"
#include "Poison.hpp"
#include "Sleep.hpp"
#include "Toxic.hpp"
#include "Trapped.hpp"
#include "Trapper.hpp"
