// AUTOGENERATED FILE, DO NOT EDIT

#pragma once

#include "BattleStateSetup.hpp"
#include "EmplaceTagFromEnum.hpp"
#include "PokemonStateSetup.hpp"
#include "SideStateSetup.hpp"
#include "StateSetupBase.hpp"
