name: Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-test.yml'
      - 'external/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'tools/**'
      - 'CMakeLists.txt'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-test.yml'
      - 'external/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'tools/**'
      - 'CMakeLists.txt'

jobs:
  linux:
    name: 'Linux: ${{matrix.cxx}}, SHF ${{matrix.use_single_header}}, ${{matrix.build_type}}'
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        cxx:
          - g++-10
          - g++-11
          - g++-12
          - g++-13
          - g++-14
          - clang++-13
          - clang++-14
          - clang++-15
          - clang++-16
          - clang++-17
          - clang++-18
        build_type: [Debug, Release]
        use_single_header: ['TRUE', 'FALSE']
        include:
          - cxx: g++-10
            other_pkgs: g++-10
            os: ubuntu-22.04
          - cxx: g++-11
            other_pkgs: g++-11
            os: ubuntu-22.04
          - cxx: g++-12
            other_pkgs: g++-12
            os: ubuntu-22.04
          - cxx: g++-13
            other_pkgs: g++-13
            os: ubuntu-24.04
          - cxx: g++-14
            other_pkgs: g++-14
            os: ubuntu-24.04
          - cxx: clang++-13
            os: ubuntu-22.04
          - cxx: clang++-14
            os: ubuntu-22.04
          - cxx: clang++-15
            os: ubuntu-22.04
          - cxx: clang++-16
            os: ubuntu-22.04
          - cxx: clang++-17
            os: ubuntu-24.04
          - cxx: clang++-18
            os: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache LLVM and Clang
        if: matrix.use_single_header == 'TRUE'
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ./llvm
          key: llvm-15.0.6
      - name: Install clang-query
        if: matrix.use_single_header == 'TRUE'
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: "15.0.6"
          directory: ./llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Add Clang Upstream
        if: startsWith(matrix.cxx, 'clang')
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          clang_version="${{matrix.cxx}}"
          version_number=${clang_version#*-}
          codename=`lsb_release -sc`

          sudo apt-add-repository --yes --update "deb http://apt.llvm.org/$codename/ llvm-toolchain-$codename-$version_number main"
          sudo apt install -yq --no-install-recommends clang-$version_number

      - name: Prepare environment
        if: matrix.other_pkgs
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends ${{matrix.other_pkgs}}

      - name: Create Single Header File
        if: matrix.use_single_header == 'TRUE'
        uses: ./.github/actions/create-headers

      - name: Remove clang-query
        if: matrix.use_single_header == 'TRUE'
        run: rm -rf ./llvm

      - name: Configure build
        working-directory: ${{runner.workspace}}
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -Bbuild -H$GITHUB_WORKSPACE \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DPOKESIM_USE_SINGLE_HEADER_FILE=${{matrix.use_single_header}} \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY:FILEPATH=${{runner.workspace}}/build/bin \
                -G "Unix Makefiles"

      - name: Build tests
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}} --target PokeSimTests

      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        run: bin/PokeSimTests
  windows:
    name: '${{matrix.os}}: SHF ${{matrix.use_single_header}}, ${{matrix.platform}} ${{matrix.build_type}}'
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        platform: [Win32, x64]
        build_type: [Debug, Release]
        use_single_header: ['TRUE', 'FALSE']
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Cache LLVM and Clang
        if: matrix.use_single_header == 'TRUE'
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ./llvm
          key: llvm-15.0.6
      - name: Install clang-query
        if: matrix.use_single_header == 'TRUE'
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: "15.0.6"
          directory: ./llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Create Single Header File
        if: matrix.use_single_header == 'TRUE'
        uses: ./.github/actions/create-headers
      
      - name: Configure build
        working-directory: ${{runner.workspace}}
        run: |
          cmake -S $Env:GITHUB_WORKSPACE                               `
                -B ${{runner.workspace}}\build                         `
                -DPOKESIM_USE_SINGLE_HEADER_FILE=${{matrix.use_single_header}} `
                -A ${{matrix.platform}}
      
      - name: Build tests
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}} --target PokeSimTests

      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        run: bin\${{matrix.build_type}}\PokeSimTests.exe
  mac:
    name: 'Mac OS: ${{matrix.cxx}}, SHF ${{matrix.use_single_header}}, ${{matrix.build_type}}'
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        cxx:
          - g++-12
          - g++-13
          - g++-14
          - clang++
        build_type: [Debug, Release]
        use_single_header: ['TRUE', 'FALSE']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache LLVM and Clang
        if: matrix.use_single_header == 'TRUE'
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ./llvm
          key: llvm-15.0.7
      - name: Install clang-query
        if: matrix.use_single_header == 'TRUE'
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: "15.0.7"
          directory: ./llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Create Single Header File
        if: matrix.use_single_header == 'TRUE'
        uses: ./.github/actions/create-headers

      - name: Configure build
        working-directory: ${{runner.workspace}}
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -Bbuild -H$GITHUB_WORKSPACE \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DPOKESIM_USE_SINGLE_HEADER_FILE=${{matrix.use_single_header}} \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY:FILEPATH=${{runner.workspace}}/build/bin \

      - name: Build tests
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}} --target PokeSimTests

      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        run: bin/PokeSimTests
