name: Update Single Header File

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'src/**'
      - 'external/**'
      - 'tools/createSingleHeaderFile.js'
  pull_request:
    branches:
      - main
    paths: 
      - 'src/**'
      - 'external/**'
      - 'tools/createSingleHeaderFile.js'

jobs:
  create-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.15

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ../llvm
          key: llvm-15.0.6
      - name: Install clang-query
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: "15.0.6"
          directory: ../llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Create Single Header File
        uses: ./.github/actions/create-headers

      - name: Commit include/PokeSim.hpp
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Milo[bot]
          message: Updating Single Header File
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
