name: Update Single Header File

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'src/**'
      - 'external/**'
      - 'tools/createSingleHeaderFile.js'
  pull_request:
    branches:
      - main
    paths: 
      - 'src/**'
      - 'external/**'
      - 'tools/createSingleHeaderFile.js'

jobs:
  create-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Single Header File
        uses: ./.github/actions/single-header-file

      - name: Commit include/PokeSim.hpp
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Milo[bot]
          message: Updating Single Header File
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
